### ISSUE TITLE
Suggestion - ignore case when providing controller and action names

### ISSUE THREAD

**Issue by ghost** [Daniel15/RouteJs#34]
My preference has always been to use a custom route provider that auto-lowercases my routes. I see that the routes are case-sensitive, but seeing as how the casing is not a factor in the @Url.Action and  other helper methods, it might help if the casing could be ignored.

Thoughts?

**Comment by boerbiet** [comment]
I found out this change breaks some functionality on our site after a colleague updated from 1.1.7 to 1.1.8. For example:

C#
```
routes.MapRoute("Arbitrary Route", "path/{variableThing}/etc/", new { controller = "X", action = "Y" }, new { variableThing = "Z" });
```
JS
```
Router.Action('X', 'Y', { variableThing: 'Z' });
```
Now when the constraints are parsed, the key variable will be "variableThing". The objects however:
```
parsedConstraints['variableThing'] = /^(Z)/

routevalues['variablething'] = 'Z'
```
Due to the lower case key the route will not match. Maybe it's intended behaviour, maybe it's an oversight, but I think it should either be addressed or mentioned in the documentation. I'll discuss with my colleagues whether or not we should go all lower case on constraint keys or downgrade to 1.1.7.

**Comment by Daniel15** [comment]
Definitely sounds like an oversight. Can you please create a separate issue
for it? I can fix this weekend (or sooner if I get some free time). Thanks!

--
Regards,
Daniel Lo Nigro
http://dan.cx/ | Twitter <http://twitter.com/Daniel15> | Facebook
<http://www.facebook.com/daaniel>
